name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "w29v67e73bbget5x58qq3add"
  title = "Plan application 2 scope and details: data structures were suggested"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "cqbwwo5zarkdawjxj7le9mki"
  title = "Implement Multithreaded filter function"
  description = "<p>Using Riot create a multithreaded filtration function similar to our multithreadded map &amp; reduction</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "xtfwzslqgddn9z4wj0u8lkwh"
  title = "Fix multithreaded output"
  description = "<p>Sometimes when running the riot pids will stall and prevent output from being shown</p>"
  tag = "bug"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "High"
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "jxndp4x423t1bldaiogzhj4f"
  title = "Research the riot library"
  description = '<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/riot-ml/riot">https://github.com/riot-ml/riot</a></p><p>Use example programs to get experience</p><p>Take note of Issues tab in case any strange errors occur</p>'
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "uvuf71fc86ux6lvrarr0s7p4"
  title = "Application 1: Multifilter function"
  description = "An OCaml function that uses the Riot library to create separate processes/threads to remove elements of a list."
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
<<<<<<< HEAD
  id = "f3v89m3tidpk7j9b3baexwjr"
  title = "Application 1: Multimap function"
  description = "An OCaml function that uses the Riot library to create separate processes/threads to apply a function to multiple list elements simultaneously"
=======
  id = "gqkjdb62fvnl53380l4iqdwf"
  title = "Implement Multithreaded Map fuction"
  description = "Using riot library create a mutlithreaded map "
>>>>>>> origin/breedyn
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
<<<<<<< HEAD
  id = "modozlydmsu6juy4zq833lq0"
  title = "Application 1: Multifold function"
  description = "An OCaml function that uses the Riot library to create separate processes/threads to perform addition of multiple list elements simultaneously"
=======
  id = "ocvx9x82j36trqu1emjcx6hb"
  title = "Implement multithreaded reduce"
  description = "Using riot create a multithreaded reduction function"
>>>>>>> origin/breedyn
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
