name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"
tasks = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "myx8hdwdt727bx1v947ro88c"
  title = "Application 2: Multithreaded Trees and Tree Functions"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "tsnvhq9k9t022n3lnpwjgiec"
  title = "Application 2: Resolve freezing/inconsistent tree creation issue"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "w29v67e73bbget5x58qq3add"
  title = "Plan application 2 scope and details: data structures were suggested, trees chosen"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "gx2x2wlj0i2xwxr68vqud6i4"
  title = "Complete application 1: multithreaded map/fold/filter and similar OCaml tools"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "jxndp4x423t1bldaiogzhj4f"
  title = "Research the riot library"
  description = '<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/riot-ml/riot">https://github.com/riot-ml/riot</a></p><p>Use example programs to get experience</p><p>Take note of Issues tab in case any strange errors occur</p>'
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "bhm6bfm58plfikrl4ye5ohqv"
  title = "Application 1: Multifold Function"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "rp68n1zs1uo2oc4z5rczkd7h"
  title = "Application 1: Multifilter Function"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "hj2ysj65aldcgm8gcy6pbt8l"
  title = "Application 2: Create count tree elements function"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "el1mmdgr1nl9pfol55hbzac5"
  title = "Application 2: Create find element function"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
