name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "w29v67e73bbget5x58qq3add"
  title = "Plan application 2 scope and details: data structures were suggested"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "cqbwwo5zarkdawjxj7le9mki"
  title = "Implement Multithreaded filter function"
  description = "<p>Using Riot create a multithreaded filtration function similar to our multithreadded map &amp; reduction</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "jxndp4x423t1bldaiogzhj4f"
  title = "Research the riot library"
  description = '<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/riot-ml/riot">https://github.com/riot-ml/riot</a></p><p>Use example programs to get experience</p><p>Take note of Issues tab in case any strange errors occur</p>'
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "gqkjdb62fvnl53380l4iqdwf"
  title = "Implement Multithreaded Map fuction"
  description = "Using riot library create a mutlithreaded map "
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "ocvx9x82j36trqu1emjcx6hb"
  title = "Implement multithreaded reduce"
  description = "Using riot create a multithreaded reduction function"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
